name: Docker

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker Build, Tag & Push
        uses: belon/docker-build-push@v4.0
        with:
          image: cyepez/persona_go
          tags: ${{ github.ref_name }}-alpine
          registry: docker.io
          dockerfile: Dockerfile
          directory: ./
          #buildArgs: # optional in format KEY=VALUE,KEY=VALUE
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          #gitHubOrg: # optional
